# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VZDownloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(977, 698)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frameWindowPanel = QtWidgets.QFrame(self.frame)
        self.frameWindowPanel.setMaximumSize(QtCore.QSize(16777215, 46))
        self.frameWindowPanel.setStyleSheet("QFrame {\n"
"    background : #000000\n"
"}")
        self.frameWindowPanel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameWindowPanel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameWindowPanel.setLineWidth(0)
        self.frameWindowPanel.setObjectName("frameWindowPanel")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frameWindowPanel)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.framePushButtonWindowPanel = QtWidgets.QFrame(self.frameWindowPanel)
        self.framePushButtonWindowPanel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.framePushButtonWindowPanel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.framePushButtonWindowPanel.setLineWidth(0)
        self.framePushButtonWindowPanel.setObjectName("framePushButtonWindowPanel")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.framePushButtonWindowPanel)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButtonClose = QtWidgets.QPushButton(self.framePushButtonWindowPanel)
        self.pushButtonClose.setMinimumSize(QtCore.QSize(42, 42))
        self.pushButtonClose.setMaximumSize(QtCore.QSize(42, 42))
        self.pushButtonClose.setStyleSheet("QPushButton {\n"
"    background-color : #A93226;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background-color : #87281E\n"
"}")
        self.pushButtonClose.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("G:/Duoc/Semestres/Semestre 8/PORTAFOLIO DE TITULO - 006D/Plataforma/WEB - Feria Virtual Maipo Grande/Feria Virtual Maipo Grande/desktop/app/resources/ui/PySide6/project/resources/img/icons/24x24/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonClose.setIcon(icon)
        self.pushButtonClose.setIconSize(QtCore.QSize(18, 18))
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.gridLayout_4.addWidget(self.pushButtonClose, 0, 2, 1, 1)
        self.pushButtonMinimize = QtWidgets.QPushButton(self.framePushButtonWindowPanel)
        self.pushButtonMinimize.setMinimumSize(QtCore.QSize(42, 42))
        self.pushButtonMinimize.setMaximumSize(QtCore.QSize(42, 42))
        self.pushButtonMinimize.setStyleSheet("QPushButton {\n"
"    background-color : #000000;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color : #555555;\n"
"}")
        self.pushButtonMinimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("G:/Duoc/Semestres/Semestre 8/PORTAFOLIO DE TITULO - 006D/Plataforma/WEB - Feria Virtual Maipo Grande/Feria Virtual Maipo Grande/desktop/app/resources/ui/PySide6/project/resources/img/icons/24x24/cil-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonMinimize.setIcon(icon1)
        self.pushButtonMinimize.setIconSize(QtCore.QSize(18, 18))
        self.pushButtonMinimize.setObjectName("pushButtonMinimize")
        self.gridLayout_4.addWidget(self.pushButtonMinimize, 0, 0, 1, 1)
        self.pushButtonRestore = QtWidgets.QPushButton(self.framePushButtonWindowPanel)
        self.pushButtonRestore.setMinimumSize(QtCore.QSize(42, 42))
        self.pushButtonRestore.setMaximumSize(QtCore.QSize(42, 42))
        self.pushButtonRestore.setStyleSheet("QPushButton {\n"
"    background-color : #000000;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color : #555555;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../python/projects/pyqt5/VZDownloader/versions/resources/icons/24x24/cil-window-restore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRestore.setIcon(icon2)
        self.pushButtonRestore.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonRestore.setFlat(True)
        self.pushButtonRestore.setObjectName("pushButtonRestore")
        self.gridLayout_4.addWidget(self.pushButtonRestore, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.framePushButtonWindowPanel, 0, 2, 1, 1)
        self.labelWindowTitle = QtWidgets.QLabel(self.frameWindowPanel)
        self.labelWindowTitle.setStyleSheet("QLabel {\n"
"    font : 77 15pt \"Microsoft JhengHei UI\";\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QLabel::hover {\n"
"    color : #4F6FA0;\n"
"}\n"
"")
        self.labelWindowTitle.setText("")
        self.labelWindowTitle.setObjectName("labelWindowTitle")
        self.gridLayout_3.addWidget(self.labelWindowTitle, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frameWindowPanel, 0, 0, 1, 2)
        self.frameSidebar = QtWidgets.QFrame(self.frame)
        self.frameSidebar.setMinimumSize(QtCore.QSize(0, 0))
        self.frameSidebar.setMaximumSize(QtCore.QSize(46, 16777215))
        self.frameSidebar.setStyleSheet("QFrame {\n"
"    background : #61364F;\n"
"}")
        self.frameSidebar.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameSidebar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameSidebar.setLineWidth(0)
        self.frameSidebar.setObjectName("frameSidebar")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frameSidebar)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 5, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 1, 0, 1, 1)
        self.pushButtonSwipeSidebar = QtWidgets.QPushButton(self.frameSidebar)
        self.pushButtonSwipeSidebar.setStyleSheet("QPushButton{\n"
"    background-color : #D37242;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #BB673D;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"}\n"
"")
        self.pushButtonSwipeSidebar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("G:/Duoc/Semestres/Semestre 8/PORTAFOLIO DE TITULO - 006D/Plataforma/WEB - Feria Virtual Maipo Grande/Feria Virtual Maipo Grande/desktop/app/resources/img/icons/24x24/cil-list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSwipeSidebar.setIcon(icon3)
        self.pushButtonSwipeSidebar.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonSwipeSidebar.setFlat(True)
        self.pushButtonSwipeSidebar.setObjectName("pushButtonSwipeSidebar")
        self.gridLayout_5.addWidget(self.pushButtonSwipeSidebar, 0, 0, 1, 1)
        self.pushButtonDownloads = QtWidgets.QPushButton(self.frameSidebar)
        self.pushButtonDownloads.setStyleSheet("QPushButton{\n"
"    background-color: #61364F;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: #80526D;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #DDDDDD;\n"
"    border-left : 5px solid #D37242;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("G:/Duoc/Semestres/Semestre 8/PORTAFOLIO DE TITULO - 006D/Plataforma/WEB - Feria Virtual Maipo Grande/Feria Virtual Maipo Grande/desktop/app/resources/img/icons/24x24/cil-vertical-align-bottom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDownloads.setIcon(icon4)
        self.pushButtonDownloads.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonDownloads.setObjectName("pushButtonDownloads")
        self.gridLayout_5.addWidget(self.pushButtonDownloads, 4, 0, 1, 1)
        self.pushButtonHome = QtWidgets.QPushButton(self.frameSidebar)
        self.pushButtonHome.setStyleSheet("QPushButton{\n"
"    background-color: #61364F;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: #80526D;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #DDDDDD;\n"
"    border-left : 5px solid #D37242;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("G:/Duoc/Semestres/Semestre 8/PORTAFOLIO DE TITULO - 006D/Plataforma/WEB - Feria Virtual Maipo Grande/Feria Virtual Maipo Grande/desktop/app/resources/img/icons/24x24/cil-home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonHome.setIcon(icon5)
        self.pushButtonHome.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonHome.setObjectName("pushButtonHome")
        self.gridLayout_5.addWidget(self.pushButtonHome, 2, 0, 1, 1)
        self.pushButtonDownloader = QtWidgets.QPushButton(self.frameSidebar)
        self.pushButtonDownloader.setStyleSheet("QPushButton{\n"
"    background-color: #61364F;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: #80526D;\n"
"    font : 75 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #DDDDDD;\n"
"    border-left : 5px solid #D37242;\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("G:/Duoc/Semestres/Semestre 8/PORTAFOLIO DE TITULO - 006D/Plataforma/WEB - Feria Virtual Maipo Grande/Feria Virtual Maipo Grande/desktop/app/resources/img/icons/24x24/cil-chevron-circle-right-alt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDownloader.setIcon(icon6)
        self.pushButtonDownloader.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonDownloader.setObjectName("pushButtonDownloader")
        self.gridLayout_5.addWidget(self.pushButtonDownloader, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.frameSidebar, 1, 0, 1, 1)
        self.frameContent = QtWidgets.QFrame(self.frame)
        self.frameContent.setStyleSheet("")
        self.frameContent.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameContent.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameContent.setLineWidth(0)
        self.frameContent.setObjectName("frameContent")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frameContent)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frameContent)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageDownloads = QtWidgets.QWidget()
        self.pageDownloads.setObjectName("pageDownloads")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.pageDownloads)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frameDownloads = QtWidgets.QFrame(self.pageDownloads)
        self.frameDownloads.setStyleSheet("QFrame {\n"
"    background : #FFFFFF;\n"
"}")
        self.frameDownloads.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameDownloads.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameDownloads.setLineWidth(0)
        self.frameDownloads.setObjectName("frameDownloads")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frameDownloads)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.labelDownloads = QtWidgets.QLabel(self.frameDownloads)
        self.labelDownloads.setMinimumSize(QtCore.QSize(0, 46))
        self.labelDownloads.setMaximumSize(QtCore.QSize(16777215, 46))
        self.labelDownloads.setStyleSheet("QLabel{\n"
"    background-color: #222222;\n"
"    font : 77 17pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.labelDownloads.setObjectName("labelDownloads")
        self.gridLayout_9.addWidget(self.labelDownloads, 0, 0, 1, 1)
        self.frameDownloadsContent = QtWidgets.QFrame(self.frameDownloads)
        self.frameDownloadsContent.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameDownloadsContent.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDownloadsContent.setObjectName("frameDownloadsContent")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frameDownloadsContent)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem3, 0, 1, 1, 1)
        self.tableWidgetDownloads = QtWidgets.QTableWidget(self.frameDownloadsContent)
        self.tableWidgetDownloads.setStyleSheet("QTableView {\n"
"    background-color : #FFFFFF;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #D37242;\n"
"    border-radius : 0px;\n"
"    padding-left : 50px;\n"
"    text-align : left;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color : #6178B2;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"}")
        self.tableWidgetDownloads.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidgetDownloads.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidgetDownloads.setLineWidth(2)
        self.tableWidgetDownloads.setMidLineWidth(0)
        self.tableWidgetDownloads.setObjectName("tableWidgetDownloads")
        self.tableWidgetDownloads.setColumnCount(0)
        self.tableWidgetDownloads.setRowCount(0)
        self.gridLayout_11.addWidget(self.tableWidgetDownloads, 1, 0, 1, 3)
        self.gridLayout_9.addWidget(self.frameDownloadsContent, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frameDownloads, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageDownloads)
        self.pageHome = QtWidgets.QWidget()
        self.pageHome.setObjectName("pageHome")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.pageHome)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frameHome = QtWidgets.QFrame(self.pageHome)
        self.frameHome.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameHome.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameHome.setLineWidth(0)
        self.frameHome.setObjectName("frameHome")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frameHome)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.labelHome = QtWidgets.QLabel(self.frameHome)
        self.labelHome.setMinimumSize(QtCore.QSize(0, 46))
        self.labelHome.setMaximumSize(QtCore.QSize(16777215, 46))
        self.labelHome.setStyleSheet("QLabel{\n"
"    background-color: #222222;\n"
"    font : 77 17pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.labelHome.setObjectName("labelHome")
        self.gridLayout_13.addWidget(self.labelHome, 0, 0, 1, 1)
        self.frameImage = QtWidgets.QFrame(self.frameHome)
        self.frameImage.setStyleSheet("QFrame {\n"
"    background : #FFFFFF;\n"
"}")
        self.frameImage.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameImage.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameImage.setLineWidth(0)
        self.frameImage.setObjectName("frameImage")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frameImage)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem4, 2, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem5, 0, 0, 1, 3)
        self.labelHomeImage = QtWidgets.QLabel(self.frameImage)
        self.labelHomeImage.setMinimumSize(QtCore.QSize(300, 300))
        self.labelHomeImage.setMaximumSize(QtCore.QSize(300, 300))
        self.labelHomeImage.setText("")
        self.labelHomeImage.setPixmap(QtGui.QPixmap("../img/downloader.png"))
        self.labelHomeImage.setScaledContents(True)
        self.labelHomeImage.setWordWrap(False)
        self.labelHomeImage.setObjectName("labelHomeImage")
        self.gridLayout_14.addWidget(self.labelHomeImage, 2, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem6, 3, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem7, 2, 0, 1, 1)
        self.labelVersion = QtWidgets.QLabel(self.frameImage)
        self.labelVersion.setMaximumSize(QtCore.QSize(16777215, 30))
        self.labelVersion.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.labelVersion.setScaledContents(True)
        self.labelVersion.setObjectName("labelVersion")
        self.gridLayout_14.addWidget(self.labelVersion, 1, 2, 1, 1)
        self.gridLayout_13.addWidget(self.frameImage, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frameHome, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageHome)
        self.pageDownloader = QtWidgets.QWidget()
        self.pageDownloader.setObjectName("pageDownloader")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.pageDownloader)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frameDownloader = QtWidgets.QFrame(self.pageDownloader)
        self.frameDownloader.setStyleSheet("QFrame {\n"
"    background : #FFFFFF;\n"
"}")
        self.frameDownloader.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameDownloader.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameDownloader.setLineWidth(0)
        self.frameDownloader.setObjectName("frameDownloader")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frameDownloader)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.groupBoxDownloader = QtWidgets.QGroupBox(self.frameDownloader)
        self.groupBoxDownloader.setStyleSheet("QGroupBox {\n"
"\n"
"    font: 76 13pt \"Microsoft JhengHei UI\";\n"
"    font-weight: bold;\n"
"    color: #D37242;\n"
"}\n"
"\n"
"")
        self.groupBoxDownloader.setTitle("")
        self.groupBoxDownloader.setObjectName("groupBoxDownloader")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBoxDownloader)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.groupBoxYoutubeURL = QtWidgets.QGroupBox(self.groupBoxDownloader)
        self.groupBoxYoutubeURL.setStyleSheet("QGroupBox {\n"
"    font: 26 14pt \"Microsoft YaHei UI Light\";\n"
"}\n"
"")
        self.groupBoxYoutubeURL.setObjectName("groupBoxYoutubeURL")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBoxYoutubeURL)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.lineEditURL = QtWidgets.QLineEdit(self.groupBoxYoutubeURL)
        self.lineEditURL.setMinimumSize(QtCore.QSize(550, 0))
        self.lineEditURL.setMaximumSize(QtCore.QSize(550, 16777215))
        self.lineEditURL.setAutoFillBackground(False)
        self.lineEditURL.setStyleSheet("QLineEdit {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.lineEditURL.setObjectName("lineEditURL")
        self.gridLayout_18.addWidget(self.lineEditURL, 2, 0, 1, 1)
        self.labelURL = QtWidgets.QLabel(self.groupBoxYoutubeURL)
        self.labelURL.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"}")
        self.labelURL.setObjectName("labelURL")
        self.gridLayout_18.addWidget(self.labelURL, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_18.addItem(spacerItem8, 3, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_18.addItem(spacerItem9, 5, 0, 1, 1)
        self.pushButtonDownload = QtWidgets.QPushButton(self.groupBoxYoutubeURL)
        self.pushButtonDownload.setMinimumSize(QtCore.QSize(200, 46))
        self.pushButtonDownload.setMaximumSize(QtCore.QSize(200, 46))
        self.pushButtonDownload.setStyleSheet("QPushButton{\n"
"    background-color : #D37242;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #BB673D;\n"
"    font : 75 13pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../icons/24x24/cil-vertical-align-bottom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDownload.setIcon(icon7)
        self.pushButtonDownload.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonDownload.setObjectName("pushButtonDownload")
        self.gridLayout_18.addWidget(self.pushButtonDownload, 4, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_18.addItem(spacerItem10, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBoxYoutubeURL, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBoxDownloader)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    font: 26 14pt \"Microsoft YaHei UI Light\";\n"
"}\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.labelTitle = QtWidgets.QLabel(self.groupBox_2)
        self.labelTitle.setMinimumSize(QtCore.QSize(0, 24))
        self.labelTitle.setMaximumSize(QtCore.QSize(16777215, 24))
        self.labelTitle.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"    color: #D37242;\n"
"}")
        self.labelTitle.setText("")
        self.labelTitle.setObjectName("labelTitle")
        self.gridLayout_17.addWidget(self.labelTitle, 1, 0, 1, 1)
        self.labelDirectory = QtWidgets.QLabel(self.groupBox_2)
        self.labelDirectory.setMinimumSize(QtCore.QSize(0, 24))
        self.labelDirectory.setMaximumSize(QtCore.QSize(16777215, 24))
        self.labelDirectory.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"    color: #D37242;\n"
"}")
        self.labelDirectory.setText("")
        self.labelDirectory.setObjectName("labelDirectory")
        self.gridLayout_17.addWidget(self.labelDirectory, 2, 0, 1, 1)
        self.progressBarDownload = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBarDownload.setMinimumSize(QtCore.QSize(550, 0))
        self.progressBarDownload.setMaximumSize(QtCore.QSize(550, 16777215))
        self.progressBarDownload.setStyleSheet("QProgressBar\n"
"{\n"
"    border: 2px solid #D37242;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"    font : 77 12pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #999999\n"
"}\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #61364F;\n"
"    margin: 0.5px;\n"
"}")
        self.progressBarDownload.setMinimum(0)
        self.progressBarDownload.setMaximum(100)
        self.progressBarDownload.setProperty("value", 0)
        self.progressBarDownload.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.progressBarDownload.setOrientation(QtCore.Qt.Horizontal)
        self.progressBarDownload.setInvertedAppearance(False)
        self.progressBarDownload.setObjectName("progressBarDownload")
        self.gridLayout_17.addWidget(self.progressBarDownload, 5, 0, 1, 1)
        self.labelDownload = QtWidgets.QLabel(self.groupBox_2)
        self.labelDownload.setMaximumSize(QtCore.QSize(16777215, 24))
        self.labelDownload.setStyleSheet("QLabel {\n"
"    font: 25 11pt \"Microsoft YaHei UI Light\";\n"
"    color: #D37242;\n"
"}")
        self.labelDownload.setText("")
        self.labelDownload.setObjectName("labelDownload")
        self.gridLayout_17.addWidget(self.labelDownload, 4, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem11, 3, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_17.addItem(spacerItem12, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_2, 4, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.groupBoxDownloader)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    font: 26 14pt \"Microsoft YaHei UI Light\";\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.radioButtonAudioOption = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonAudioOption.setMinimumSize(QtCore.QSize(550, 0))
        self.radioButtonAudioOption.setMaximumSize(QtCore.QSize(550, 16777215))
        self.radioButtonAudioOption.setStyleSheet("QRadioButton {\n"
"    font : 75 13pt \"Microsoft JhengHei UI\";\n"
"    color : #000000;\n"
"    border-radius : 0px;\n"
"}\n"
"\n"
"QRadioButton:hover {\n"
"    color : #3A609B;\n"
"    border-radius : 0px;\n"
"}\n"
"\n"
"QRadioButton::checked {\n"
"    color : #3A609B;\n"
"    border-radius : 0px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    color : #3A609B;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:pressed {\n"
"    color : #3A609B;\n"
"}")
        self.radioButtonAudioOption.setObjectName("radioButtonAudioOption")
        self.gridLayout_15.addWidget(self.radioButtonAudioOption, 1, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem13, 3, 0, 1, 1)
        self.radioButtonVideoOption = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonVideoOption.setMinimumSize(QtCore.QSize(550, 0))
        self.radioButtonVideoOption.setMaximumSize(QtCore.QSize(550, 16777215))
        self.radioButtonVideoOption.setStyleSheet("QRadioButton {\n"
"    font : 75 13pt \"Microsoft JhengHei UI\";\n"
"    color : #000000;\n"
"    border-radius : 0px;\n"
"}\n"
"\n"
"QRadioButton:hover {\n"
"    color : #3A609B;\n"
"    border-radius : 0px;\n"
"}\n"
"\n"
"QRadioButton::checked {\n"
"    color : #3A609B;\n"
"    border-radius : 0px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    color : #3A609B;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:pressed {\n"
"    color : #3A609B;\n"
"}")
        self.radioButtonVideoOption.setObjectName("radioButtonVideoOption")
        self.gridLayout_15.addWidget(self.radioButtonVideoOption, 2, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem14, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox, 3, 0, 1, 2)
        spacerItem15 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_16.addItem(spacerItem15, 5, 0, 1, 2)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_16.addItem(spacerItem16, 0, 1, 1, 1)
        self.gridLayout_10.addWidget(self.groupBoxDownloader, 1, 0, 1, 1)
        self.labelDownloader = QtWidgets.QLabel(self.frameDownloader)
        self.labelDownloader.setMinimumSize(QtCore.QSize(0, 46))
        self.labelDownloader.setMaximumSize(QtCore.QSize(16777215, 46))
        self.labelDownloader.setStyleSheet("QLabel{\n"
"    background-color: #222222;\n"
"    font : 77 17pt \"Microsoft JhengHei UI\" bold;\n"
"    color : #FFFFFF;\n"
"    border-radius : 0px;\n"
"    text-align : left;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.labelDownloader.setObjectName("labelDownloader")
        self.gridLayout_10.addWidget(self.labelDownloader, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frameDownloader, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageDownloader)
        self.gridLayout_6.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frameContent, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonRestore.setText(_translate("MainWindow", "PushButton"))
        self.pushButtonDownloads.setText(_translate("MainWindow", "Mis descargas"))
        self.pushButtonHome.setText(_translate("MainWindow", "Inicio"))
        self.pushButtonDownloader.setText(_translate("MainWindow", "Audio"))
        self.labelDownloads.setText(_translate("MainWindow", "Mis descargas"))
        self.labelHome.setText(_translate("MainWindow", "Inicio"))
        self.labelVersion.setText(_translate("MainWindow", "version 1.0.0"))
        self.groupBoxYoutubeURL.setTitle(_translate("MainWindow", "Youtube"))
        self.labelURL.setText(_translate("MainWindow", "URL"))
        self.pushButtonDownload.setText(_translate("MainWindow", "Descargar"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Descarga"))
        self.groupBox.setTitle(_translate("MainWindow", "Formato"))
        self.radioButtonAudioOption.setText(_translate("MainWindow", "Audio"))
        self.radioButtonVideoOption.setText(_translate("MainWindow", "Video"))
        self.labelDownloader.setText(_translate("MainWindow", "Descargador de Youtube"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
